version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_fullstack_java
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./create_database.mysql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
